# Generated by Django 4.2 on 2026-02-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=20),
        ),
    ]
