# Generated by Django 4.2 on 2026-02-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada')], default='en', max_length=5),
        ),
    ]
