# Generated by Django 4.2 on 2026-02-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_likedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload MP3 or other audio format (MP3, WAV, OGG supported)', null=True, upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral'), ('angry', 'Angry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
