# Generated by Django 4.2 on 2026-02-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song_audio_file_song_duration_alter_song_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_url',
            field=models.URLField(blank=True, help_text='Link to lyrics (Genius.com, AZLyrics, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Upload album art image (JPG, PNG)', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to thumbnail image', null=True),
        ),
    ]
